/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));

char *__env[1] = { 0 };
char **environ = __env;

/* Functions */
/**
 * @brief Stub for semihosting monitor initialization.
 */
void initialise_monitor_handles()
{
}

/**
 * @brief Return a fixed process identifier for the embedded runtime.
 * @return Always returns `1`.
 */
int _getpid(void)
{
  return 1;
}

/**
 * @brief Report that POSIX signal delivery is unsupported.
 * @param pid Unused process identifier.
 * @param sig Unused signal number.
 * @return Always returns `-1` and sets `errno` to `EINVAL`.
 */
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

/**
 * @brief Terminate execution by trapping in an infinite loop.
 * @param status Exit status passed to the low-level runtime.
 */
void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

/**
 * @brief Read bytes from the configured low-level input hook.
 * @param file Unused file descriptor.
 * @param ptr Destination buffer.
 * @param len Number of bytes requested.
 * @return Number of bytes read.
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int data_index;

  for (data_index = 0; data_index < len; data_index++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

/**
 * @brief Write bytes using the configured low-level output hook.
 * @param file Unused file descriptor.
 * @param ptr Source buffer.
 * @param len Number of bytes to write.
 * @return Number of bytes written.
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int data_index;

  for (data_index = 0; data_index < len; data_index++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

/**
 * @brief Report that close is unsupported for this runtime.
 * @param file Unused file descriptor.
 * @return Always returns `-1`.
 */
int _close(int file)
{
  (void)file;
  return -1;
}

/**
 * @brief Mark the file descriptor as a character device.
 * @param file Unused file descriptor.
 * @param st Output stat structure.
 * @return Always returns `0`.
 */
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
 * @brief Report all file descriptors as terminal-like devices.
 * @param file Unused file descriptor.
 * @return Always returns `1`.
 */
int _isatty(int file)
{
  (void)file;
  return 1;
}

/**
 * @brief Report that seeking is unsupported for this runtime.
 * @param file Unused file descriptor.
 * @param ptr Unused offset.
 * @param dir Unused seek origin.
 * @return Always returns `0`.
 */
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
